---

 - hosts: localhost
   remote_user: root
   gather_facts: true
   tasks:
     - name: check container exist or not
       command: "docker ps -q --filter 'name=tomcatJen1'"
       register: found_container
     - debug: msg="{{found_container.stdout}}"
     
     - name: check stop container exist or not
       command: "docker ps -aq --filter 'name=tomcatJen1'"
       register: found_stop_container

     - debug: msg="{{found_stop_container.stdout}}"

     - name: stop and remove docker container already running
       command: "docker stop tomcatJen1;docker rm -f tomcatJen1"
       when: found_container.stdout != ""
   
     - name: remove docker container already running
       command: "docker rm -f tomcatJen1"
       when: found_stop_container.stdout != ""

     - name: create docker image from docker file
       command: "docker build -t tomcatjen:{{New_Project_version}} ."
       register: docker_res
     - name: run docker container
       command: "docker run --name tomcatJen1 -d -p 8086:8080 tomcatjen:{{New_Project_version}}"
   
